# Generated by Django 4.2.6 on 2023-11-30 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegressionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date that the model was created')),
                ('legacy_date', models.DateTimeField(blank=True, null=True, verbose_name='Date that the model was deprecated')),
                ('training_file', models.CharField(max_length=100, verbose_name='File used to train the model')),
                ('regression_file', models.CharField(max_length=100, verbose_name='File of the model')),
                ('roc_auc', models.FloatField(verbose_name='ROC AUC of the model')),
            ],
        ),
    ]
