# Generated by Django 4.2.6 on 2023-11-30 13:26

from django.db import migrations, models
from pandas import read_parquet
from predict.models import RegressionModel
from os.path import join


def first_training(apps, schema_editor):
    data = read_parquet(join("storage", "training_sets","training_set.parquet"))
    score, regression_file = RegressionModel.train_new_model(data)
    model = RegressionModel.objects.create(training_file="training_set.parquet", regression_file=regression_file, roc_auc=score)
    model.save()    
    
class Migration(migrations.Migration):
    dependencies = [
        ('predict', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(first_training),
    ]
